Добавил функцию подсчета символов поста
mikhailxrp/my_study_project pull request #1
Opened 2023-07-13 09:50 UTC by mikhailxrp

2023-07-13 17:35 UTC, burtovoy commented
Чтобы мне приходило оповещение - нужно добавить меня в Reviewers (в самом pr, справа)

2023-07-14 00:05 UTC, burtovoy requested changes

2023-07-14 00:05 UTC, burtovoy commented on public/assets/post_size.js
> +    /^((ftp|http|https):\/\/)?(www\.)?([A-Za-zА-Яа-я0-9]{1}[A-Za-zА-Яа-я0-9\-]*\.?)*\.{1}[A-Za-zА-Яа-я0-9-]{2,8}(\/([\w#!:.?+=&%@!\-\/])*)?/;
На курсе не используем регулярки. Практикуемся в написании кода, а не гуглении регулярок )

2023-07-14 00:05 UTC, burtovoy commented on public/assets/post_size.js
> +  for(let str of arr){
Используем forEach

2023-07-14 19:50 UTC, mikhailxrp commented on public/assets/post_size.js
> +  for(let str of arr){
Полностью переделал функцию postSize с учетом всех рекомендаций, Без регулярных выражений и прочего.

2023-07-14 19:51 UTC, mikhailxrp commented
Полностью переделал функцию postSize с учетом всех рекомендаций без регулярных выражений и прочего.

2023-07-14 20:34 UTC, mikhailxrp commented
Убрал все глобальные переменные

2023-07-16 11:24 UTC, merged