Написал функцию проверки email и тесты к этой функции
mikhailxrp/my_study_project pull request #7
Opened 2023-08-12 06:31 UTC by mikhailxrp

Помоему не много напутал с ветками.. Да тут использовал регулярное выражение, нописал его сам.

2023-08-12 06:32 UTC, mikhailxrp commented
Нет нормально все с ветками проверил

2023-08-13 12:57 UTC, mikhailxrp commented
Переписал функцию без использования регулярных выражений.

2023-08-14 11:20 UTC, burtovoy requested changes

2023-08-14 11:20 UTC, burtovoy commented on public/assets/email_is_valid.js
> +  const dictionary = [
давай без списка доменов. давай реализуем тот же алгоритм, чтобы был в ругулярке - но без регулярок

2023-08-14 11:20 UTC, burtovoy commented on public/assets/index.js
> +
лишние изменения не должны попадать в PR. Оформлять отдельным PR

2023-08-14 18:03 UTC, mikhailxrp commented
Исправил алгоритм валидации email

2023-08-15 19:03 UTC, burtovoy requested changes

2023-08-15 19:03 UTC, burtovoy commented on public/assets/email_is_valid.js
> +  if (str.includes('@') && str.includes('.') && !str.includes('@.')) {
какая-то слабенькая проверка ) @ffff.ru пройдет, например

2023-08-17 13:07 UTC, mikhailxrp commented on public/assets/email_is_valid.js
> +  const dictionary = [
Добавил новое условие для валидации email

2023-08-17 13:08 UTC, mikhailxrp commented on public/assets/email_is_valid.js
> +  if (str.includes('@') && str.includes('.') && !str.includes('@.')) {
Добавилновое условие для валидации email

2023-08-18 13:44 UTC, merged